repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        exclude: backend/widgets/timeslot/services.py|backend/widgets/timeslot/views.py
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
